### ISSUE TITLE
Bag filename has malformed timestamp

### ISSUE THREAD

**Issue by valschmidt** [rolker/remote_control#1] opened 2019-02-20 19:55 UTC
remote_control is producing bag files whose filename contains a time stamp of 1970-01-01T00-00-00 rather than the file creation time.

**Comment by rolker** [comment] 2019-02-20 22:08
This was caused by using rospy.Time instead of the python's datetime. When is simulation mode, rospy.Time returns 0 until the simulator has published times. Just committed a fix for this.

**Closed as completed by rolker** 2019-02-20 22:08 UTC
